CREATE TABLE `ICTCollab_IntellCont_Updated` (
  `PUB_ID` int COLLATE utf8_bin NOT NULL AUTO_INCREMENT,
  `DMUSERID` varchar(20) COLLATE utf8_bin NOT NULL,
  `CONID` varchar(20) COLLATE utf8_bin NOT NULL,
  ` USER_REFERENCE_CREATOR` varchar(3) COLLATE utf8_bin NOT NULL,
  `CONTRIBUTORLIST` text COLLATE utf8_bin NOT NULL,
  `CONTRIBUTORLIST_ID` varchar(4000) COLLATE utf8_bin NOT NULL,
  `CONTYPE` varchar(255) COLLATE utf8_bin NOT NULL,
  `CONTYPEOTHER` varchar(255) COLLATE utf8_bin NOT NULL,
  `STATUS` varchar(50) COLLATE utf8_bin NOT NULL,
  `CLASSIFICATION` varchar(255) COLLATE utf8_bin NOT NULL,
  `TITLE` varchar(1024) COLLATE utf8_bin NOT NULL,
  `TITLE_SECONDARY` varchar(1024) COLLATE utf8_bin NOT NULL,
  `PUBLISHER` varchar(512) COLLATE utf8_bin NOT NULL,
  `PUBCTYST` varchar(255) COLLATE utf8_bin NOT NULL,
  `PUBCNTRY` varchar(255) COLLATE utf8_bin NOT NULL,
  `VOLUME` varchar(255) COLLATE utf8_bin NOT NULL,
  `ISSUE` varchar(512) COLLATE utf8_bin NOT NULL,
  `PAGENUM` varchar(512) COLLATE utf8_bin NOT NULL,
  `EDITORS` varchar(255) COLLATE utf8_bin NOT NULL,
  `ISBNISSN` varchar(500) COLLATE utf8_bin NOT NULL,
  `PUBMED` varchar(50) COLLATE utf8_bin NOT NULL,
  `PMCID` varchar(50) COLLATE utf8_bin NOT NULL,
  `REFEREED` varchar(50) COLLATE utf8_bin NOT NULL,
  `PUBLICAVAIL` varchar(50) COLLATE utf8_bin NOT NULL,
  `DTM_PUB` varchar(50) COLLATE utf8_bin NOT NULL,
  `DTD_PUB` varchar(50) COLLATE utf8_bin NOT NULL,
  `DTY_PUB` varchar(50) COLLATE utf8_bin NOT NULL,
  `PUB_START` varchar(50) COLLATE utf8_bin NOT NULL,
  `PUB_END` varchar(50) COLLATE utf8_bin NOT NULL,
  `KEYWORDS` varchar(4000) COLLATE utf8_bin NOT NULL,

  PRIMARY KEY (PUB_ID)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

INSERT INTO ICTCollab_IntellCont_Updated (
      `DMUSERID`,`CONID`,` USER_REFERENCE_CREATOR`,`CONTRIBUTORLIST`,`CONTYPE`,`CONTYPEOTHER`,`STATUS`,`CLASSIFICATION`,`TITLE`,`TITLE_SECONDARY`,`PUBLISHER`,`PUBCTYST`,`PUBCNTRY`,`VOLUME`,`ISSUE`,`PAGENUM`,`EDITORS`,`ISBNISSN`,`PUBMED`,`PMCID`,`REFEREED`,`PUBLICAVAIL`,`DTM_PUB`,`DTD_PUB`,`DTY_PUB`,`PUB_START`,`PUB_END`,`KEYWORDS` )
SELECT `DMUSERID`,`CONID`,` USER_REFERENCE_CREATOR`,`CONTRIBUTORLIST`,`CONTYPE`,`CONTYPEOTHER`,`STATUS`,`CLASSIFICATION`,`TITLE`,`TITLE_SECONDARY`,`PUBLISHER`,`PUBCTYST`,`PUBCNTRY`,`VOLUME`,`ISSUE`,`PAGENUM`,`EDITORS`,`ISBNISSN`,`PUBMED`,`PMCID`,`REFEREED`,`PUBLICAVAIL`,`DTM_PUB`,`DTD_PUB`,`DTY_PUB`,`PUB_START`,`PUB_END`,`KEYWORDS`
FROM ICTCollab_IntellCont;